// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Core.Models.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<Guid>("EntityId");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<bool>("Published");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("Core.Models.CatalogProduct", b =>
                {
                    b.Property<Guid>("ProductId");

                    b.Property<Guid>("CatalogId");

                    b.HasKey("ProductId", "CatalogId");

                    b.HasIndex("CatalogId");

                    b.ToTable("CatalogProducts");
                });

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Core.Models.Packaging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Packagings");
                });

            modelBuilder.Entity("Core.Models.PackagingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<Guid>("PackagingId");

                    b.HasKey("Id");

                    b.HasIndex("PackagingId");

                    b.ToTable("PackagingType");
                });

            modelBuilder.Entity("Core.Models.Pricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<decimal>("Price");

                    b.Property<Guid>("ProductId");

                    b.Property<Guid>("TierId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TierId");

                    b.ToTable("Pricings");
                });

            modelBuilder.Entity("Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<decimal>("FactoryPrice");

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Name");

                    b.Property<Guid>("PackagingTypeId");

                    b.Property<decimal>("ReOrderLevel");

                    b.Property<int>("StockType");

                    b.Property<Guid>("SubBrandId");

                    b.Property<Guid>("SubCategoryId");

                    b.Property<Guid>("UnitOfMeasureId");

                    b.Property<Guid>("VatId");

                    b.HasKey("Id");

                    b.HasIndex("PackagingTypeId");

                    b.HasIndex("SubBrandId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("VatId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core.Models.SubBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BrandId");

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("SubBrand");
                });

            modelBuilder.Entity("Core.Models.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("Core.Models.Tier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Core.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<decimal>("Grammage");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<decimal>("PackSize");

                    b.Property<decimal>("PalletSize");

                    b.Property<Guid>("UnitOfMeasureTypeId");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureTypeId");

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("Core.Models.UnitOfMeasureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasureTypes");
                });

            modelBuilder.Entity("Core.Models.Vat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<decimal>("Rate");

                    b.Property<Guid>("VatCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("VatCategoryId");

                    b.ToTable("Vats");
                });

            modelBuilder.Entity("Core.Models.VatCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VatCategory");
                });

            modelBuilder.Entity("Core.Models.CatalogProduct", b =>
                {
                    b.HasOne("Core.Models.Catalog", "Catalog")
                        .WithMany("CatalogProducts")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Product", "Product")
                        .WithMany("CatalogProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.PackagingType", b =>
                {
                    b.HasOne("Core.Models.Packaging", "Packaging")
                        .WithMany("PackagingTypes")
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Pricing", b =>
                {
                    b.HasOne("Core.Models.Product", "Product")
                        .WithMany("ProductPricings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Product", b =>
                {
                    b.HasOne("Core.Models.PackagingType", "PackagingType")
                        .WithMany()
                        .HasForeignKey("PackagingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.SubBrand", "SubBrand")
                        .WithMany()
                        .HasForeignKey("SubBrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Vat", "Vat")
                        .WithMany()
                        .HasForeignKey("VatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.SubBrand", b =>
                {
                    b.HasOne("Core.Models.Brand", "Brand")
                        .WithMany("SubBrands")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.SubCategory", b =>
                {
                    b.HasOne("Core.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.UnitOfMeasure", b =>
                {
                    b.HasOne("Core.Models.UnitOfMeasureType", "UnitOfMeasureType")
                        .WithMany("UnitOfMeasures")
                        .HasForeignKey("UnitOfMeasureTypeId");
                });

            modelBuilder.Entity("Core.Models.Vat", b =>
                {
                    b.HasOne("Core.Models.VatCategory", "VatCategory")
                        .WithMany("Vats")
                        .HasForeignKey("VatCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
